def help(mode):
    if mode in ["start", "sta"]:
        print()
        print(f"          HELP PAGE FOR \"{mode}\"")
        print()
        print("Command: python3 hi.py start")
        print("            OR")
        print("         python3 hi.py sta")
        print()
        print("This command starts the timer, afterwards it ends the program, to end the started timer type \"python3 hi.py sto\"\n")
        print("When imputed the code will return the follwoing strings")
        print("Started at: XX:XX\nData: XX-XX-XXXX\nID_Date: XXXXXX")
    elif mode in ["stop", "sto"]:
        print()
        print(f"          HELP PAGE FOR \"{mode}\"")
        print()
        print("Command: python3 hi.py stop")
        print("            OR")
        print("         python3 hi.py sto")
        print()
        print("This command stops the curret running timer, if the timer is not running, then nothing will happen\n")
        print("When imputed the code will return the follwoing strings:")
        print("Started at: XX:XX\nData: XX-XX-XXXX\nID_Date: XXXXXX")
    elif mode in ["help", "?"]:
        print()
        print(f"          HELP PAGE FOR \"{mode}\"")
        print()
        print("Command: python3 hi.py help")
        print("            OR")
        print("         python3 hi.py ?")
        print()
        print("This command dispales the documintation for each command, you can add a second command for each of the commands to dysplay documinattion for that spesific command\n")
    elif mode in ["summary", "s"]:
        print()
        print(f"          HELP PAGE FOR \"{mode}\"")
        print()
        print("Command: python3 hi.py summary")
        print("            OR")
        print("         python3 hi.py s")
        print()
        print("This command prints the summary of the most reasiont data")
    elif mode in ["data", "d"]:
        print()
        print(f"          HELP PAGE FOR \"{mode}\"")
        print()
        print("Command: python3 hi.py data")
        print("            OR")
        print("         python3 hi.py d")
        print()
        print("Prints out a table of the raw data collected you can however sift throught the responces using a seccond argument")
        print()
        print("Command: python3 hi.py d t")
        print("Returns the data collected only today")
        print()
        print("Command: python3 hi.py d c")
        print("Returns the data points for each day where that point has the highest cummulative time")
        print()
        print("Command: python3 hi.py d M")
        print("Returns the max time studied in one go for each day")
        print()
        print("Command: python3 hi.py d m")
        print("Returns the min time studied in one go for each day")
    elif mode in ["t", "time"]:
        print()
        print(f"          HELP PAGE FOR \"{mode}\"")
        print()
        print("Command: python3 hi.py time")
        print("            OR")
        print("         python3 hi.py t")
        print()
        print("Displayes the current study timer, if not studing, will produce same as \"python3 hi.py s\"")
    elif mode in ["dis", "display"]:
        print()
        print(f"          HELP PAGE FOR \"{mode}\"")
        print()
        print("Command: python3 hi.py display")
        print("            OR")
        print("         python3 hi.py dis")
        print()
        print("Displayes a visual graph of ur time sudied\n")
        print()
        print("Command: python3 hi.py dis n X Y")
        print("X HAS TO BE AN INTIGER, WILL CRASH IF IT IS NOT!!!")
        print("Displayes the normal view with X lines seperating them and starting from the Yth hr in the day")
        print()
        print("Command: python3 hi.py a")
        print("THIS MODE IS NOT WORKING AS OF RIGHT NOW")
        print("same as normal but the dates start from when u started using the program")
    else:
        print()
        print("     HELLO AND WELLCOME TO THE STUDING THING!!!\n")
        print("The following is a list of command arguments that can be added to the end of the \n\"python3 hi.py\" call that can be used to make this program do spesific things")
        print('''\nArgument |Short Cut | What it dose
---------|----------|------------------------------------------------------------------------------
start    |sta       | Begins a new timer
stop     |sto       | Ends the currently running timer
help     |?         | Help, dyspalys the helps screan
summary  |s         | Summerises the current and/or last timer
data     |d         | Dysplayes all the users previousely stored data in output.csv
time     |t         | Displayes the current study timer, if not studing, will produce same as sum
display  |dis       | displayes a visual to show the hourse u have studied
''')